table Test
	lineageTag: 9fa3402a-5058-4181-82a4-602c33df474f

	column a
		dataType: int64
		formatString: 0
		lineageTag: d5a50bb4-af70-4c19-966d-d285dcb8e06b
		summarizeBy: sum
		sourceColumn: a

		annotation SummarizationSetBy = Automatic

	column b
		dataType: string
		lineageTag: 71464cc1-0d8a-4389-9afa-b8662a16e755
		summarizeBy: none
		sourceColumn: b

		annotation SummarizationSetBy = Automatic

	partition Test = m
		mode: import
		source =
				let
				  源 = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i45WMlTSUUpJUYrViVYyAjLT06rAbGMwWyk2FgA=", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [a = _t, b = _t]),
				  已更改列类型 = Table.TransformColumnTypes(源, {{"a", Int64.Type}, {"b", type text}}, "zh-Hans")
				in
				  已更改列类型

	annotation PBI_NavigationStepName = 导航

	annotation PBI_ResultType = Table

